
import { Poppins } from "next/font/google";
import "../../styles/globals.css";

import Header from '@/components/header/index';

import { SessionProvider } from "next-auth/react";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "Tasks",
  description: "Generated by create next app",
  icons: "./favIcon.png"
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <SessionProvider>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
